### ISSUE TITLE
Can't replicate Dish TV remote

### ISSUE THREAD

**Issue by uudruid74** [davorf/BlackBeanControl#14]
This is more of a support issue (or maybe a desperate cry for help) than a bug since this script is working exactly like the official Android APK.  What is weird though is that the Android APK has a built-in remote for Dish that works fine.  However, the remote is basically labelled in Chinese and it won't let edit it.  I also want to make a custom remote with the volume keys from a Logitech surround system (the TV and DishTV volume controls do nothing).  Naturally, the app lets you create a remote and "learn" the keys.  The keys learn fine, but don't work when played back!

The built-in remote works just fine, but I can't duplicate it.  Commands are being recorded, as shown here:
```
GUIDE = 26009c010ec90f5c0e360e5c0f350f5c0f5b0f5c0f5a105c0f5c0e5c0f5c0e5c0f5c0f5c0e5c0fca0e5c0f350f5c0e360f5c0e5c0f5c0e5c0f5c0e5c0f5c0f5c0e5c0f5c0e5c0f5b0fca0e5d0e360f5c0e360d5d0f5c0e5c0f5c0f5c0e5c0f5c0e5a105d0e5c0e5d0e5d12c60e5d0e360e5c0f350f5c0f5c0e5c0f5c0e5c0f5c0e5c0f5c0e5d0e5c0f5c0e5c0fca0e5c0f350f5c0e360f5c0e5c0f5c0e5c0f5c0e5d0e5c0e5d0e5c0e5d0e5c0f5c0eca0f5c0e360f5c0d370e5c0f5c0e5c0f5c0f5c0e5c0f5c0e5c0f5c0e5c0f5c0e5d0eca0e5d0e360e5c0f350f5c0f5c0e5c0f5c0e5c0f5c0e5c0f5c0e5d0e5c0f5c0e5c0fca0e5c0f350f5c0e360f5c0e5c0f5c0e5c0f5c0e5c0f5c0f5c0e5c0f5c13570f5c0eca0f5c0e360f5c0e360e5c0f5c0e5d0e5c0f5c0e5c0f5c0e5c0f5c0e5c0f5c0e5d0eca0f5c0e360e5c0e370e5c0f5c0d5d0f5c0d5d0e5d0e5c0e5d115a0d5d0e5d0d5d0ecb0d5d0e360e5d0e360e5d0d5d0e5d0e5c0e5d0e5d0d5d0e5d0d5d0e5d0d5d0e5d0eca0e5d0e360d5e0d370d5d0d5e0d5e0c5e0d5e0d5d0d5e0d5d0d5e0d5d0d5e0d5e0d000d05000000000000000000000000
CANCEL = 260014010fc80f5c0f350f5c0e5c0f360e5c0f5c0e5c0f5c0e5c0f5c0e5c0f5c0f5c0e5c0f5c0eca0f5c0e360f5b0f5c0f350f5c0e5c0f5c0e5c0f5c0f5c0e5c0f5c0e5c0f5c0e5c0fca0e5c0f360e5c0f5c0e360e5c0f59125b0f5c0f5c0e5c0f5c0e5c0f5c0f5b0f5c0fc90f5c0f350f5c0e5c0f360e5c0f5c0e5c0f5c0e5c0f5c0f5b0f5c0f5c0e5c0f5c0eca0f5c0e360f5b0f5c0f350f5c0e5c0f5c0e5c0f5c0f5c0e5c0f5c0e5c0f5c0e5c0fca0e5c0f360e5c0f5c0e360e5c0f5c0f5c0e5c0f5c0e5c0f5c0e5c0f5c0f5b0f5c0fc90f5c0f350f5c0e5c0f360e5c0f5c0e5c0f5c0e5c0f5c0f5b0f5c0f5c0e5c0f5c0eca0f5c0e360f5b0f5c0f350f5c0e5c0f5c0f5b0f5c0f5c0e5c0f5c0e5c0f5c0e5c0f000d0500000000
```
but those commands look a bit long in the tooth!   It looks like the Android app is storing in a database format.  Should I grab some pcap files and wireshark it?

But ... thank you SOO much for all the work that has been done on this.  The best thing about buying cheap crap from China is that it's cheap enough that someone else has probably already bought one just to play with it and reverse engineer it.  The expensive stuff is purchased by people that don't take things apart!

**Comment by davorf** [comment]
Hello!

You should just put a script into learning mode (by sending a command not already learned) and learn a command that way. The command storage depends on the application itself (if it's being encrypted or not). I haven't seen any remote command (tried a lot of different remotes) that couldn't be learned by the script itself. 

Best regards,
Davor

**Comment by davorf** [comment]
Hello! 

Since there aren't any new information regarding this issue, I will close it. If you have any other questions or you need help, feel free to open a new one. 

Best regards,
Davor
