### ISSUE TITLE
Not limited to RM mini - works perfect with RM pro

### ISSUE THREAD

**Issue by darth-hp** [davorf/BlackBeanControl#15]
I guess @davorf you had no chance to test other devices. I just tested it on my RM pro and it works perfect (IR + RF).

**Comment by davorf** [comment]
Hello!

Since I have RM3 mini only, I haven't had chance to test the script with any other Broadlink device. It's good to know that it works with other devices too. Thank you for the test results. 

Best regards, 
Davor

**Comment by claell** [comment]
Thanks for the information. Maybe you should add this to the readme, so interested persons (like me) don't have to search for it.
