### ISSUE TITLE
How to import commands from an existing configuration

### ISSUE THREAD

**Issue by vijayg78** [davorf/BlackBeanControl#17]
Hi,
In the RMPRO mobile app, there are options to search for remote and add it to your configuration. In such a case, if I use a remote imported from the app, can I generate the command section by any automatic way?
Regards,
Vijay

**Comment by darth-hp** [comment]
This is what I used https://github.com/NightRang3r/Broadlink-e-control-db-dump

**Comment by davorf** [comment]
Hello!

I'm really not familiar with that application, because I don't have RM Pro, You can try a script @hphde suggested, and copy/paste those codes into BlackBeanControl.ini. It would be great if you could inform us about your findings.

Best regards,
Davor

**Comment by davorf** [comment]
Hello!

Since there wasn't any changes regarding this issue, I will close it. If you have any other questions or suggestions, feel free to open a new one.

Best regards,
Davor
