### ISSUE TITLE
How do I send IR commands?

### ISSUE THREAD

**Issue by iisquazar** [davorf/BlackBeanControl#18]
Hi there,
Probably a stupid question, but how do you send IR commands?
The readme only seems to evolve around getting IR commands in the database (.ini file)...
Maybe good to add to the Read.me?

**Comment by davorf** [comment]
Hello!

You've probably missed a part about command name in the readme file:

`Command name - mandatory parameter. If the script is called with a command name not contained in the configuration file (BlackBeanControl.ini), it will start a learning process. After putting RM 3 Mini in the learning state, IR command should be sent to RM 3 Mini (usually a button press on the remote control). When defined timeout expires, captured IR command will be saved in the configuration file - in the [Commands] section. In case the script is called with a command name contained in the configuration file, it will send that command to RM 3 Mini.`

Anyway, a long story short, first time you call a command (before a command is saved to BlackBeanControl.ini), it will start learning process. After that (after a command is saved to BlackBeanControl.ini), it will send that IR command to a Broadlink device. So, it's the same command used for learning and sending a command (-C [Command name]).

Best regards,
Davor

**Comment by davorf** [comment]
Hello!

Since there wasn't any changes regarding this issue, I will close it. If you have any other questions or suggestions, feel free to open a new one.

Best regards,
Davor

**Comment by iisquazar** [comment]
Hi Davorf,

Many thanks for your help, using your code for a few months now without any
hickups!

Best,
Daniel

Op 12 jun. 2017 09:51 schreef "davorf" <notifications@github.com>:
