### ISSUE TITLE
Can't learn Dish Remote

### ISSUE THREAD

**Issue by uudruid74** [davorf/BlackBeanControl#19]
I don't know how I missed your comments on issue #14, but I can not learn that remote with the script nor the original app.  I think that is why the original app has that remote as a built-in.

Any idea how to proceed?   What if I get you network dumps of the original/working app remote in use.  Could you make a config based on that?

**Comment by davorf** [comment]
Hello!

I can try to take a look at the network dumps and see if I can extract codes. What Broadlink device are you using? Commands you've attached to the original issue look a bit too long.

**Comment by davorf** [comment]
Hello!

Since there wasn't any changes regarding this issue, I will close it. If you have any other questions or suggestions, feel free to open a new one.

Best regards,
Davor
