### ISSUE TITLE
Thanks for the BlackBeanControl :) / Are there more insights about the need for the dummy command?

### ISSUE THREAD

**Issue by abeulich** [davorf/BlackBeanControl#2]
Hi, I've been using your python script recently and I was able to successfully send commands to the RM Mini 3 and have them executed. 

While working on this I was wondering if you made additional progress regarding the need to send a dummy command before every real command? 

When capturing the traffic to the RM Mini there's no additional (other than the 'command') packet going directly to the RM and I was hoping we could get around having to send the dummy command to keep the RM responding.

Best regards, Alex

**Comment by davorf** [comment]
Hello!

I've managed to isolate a parts of an UDP payload that changes every time you send a command (and replaced them with random hex string), so, in the new version, there is no need for a dummy command. 

Best regards,
Davor

**Comment by abeulich** [comment]
Hi Davor, thanks for posting this info. In the meantime I found out the same thing when I looked more closely at the tcpdump output for repeated keypresses :) and I've also created a version, that randomizes parts of the payload. I didn't find the time to post it here, but your version is more elegant anyway. 

Best regards, Alex
