### ISSUE TITLE
No module named broadlink

### ISSUE THREAD

**Issue by mavris** [davorf/BlackBeanControl#20]
Hi,
I set BlackBean on Raspberry and I am trying to record my first command and I get this error:

**[20:58:12] openhabian@openHABianPi:/usr/BroadLink/BlackBeanControl$ python BlackBeanControl.py -c SwitchTV**
```
Traceback (most recent call last):
  File "BlackBeanControl.py", line 3, in <module>
    import broadlink, configparser
ImportError: No module named broadlink

```

**Comment by mavris** [comment]
My bad! Noob error.
I missed the instruction to download and install https://github.com/mjg59/python-broadlink
(Perhaps it will be nice to add as a hyperlink so other guys won't miss it). Thanks for this great lib.

**Comment by davorf** [comment]
Hello!

I didn't want to add a hyperlink, because this package contains Key and IV, and I doubt they are acquired legally. That's the reason I've just listed a github account and package name. 

Best regards,
Davor

**Comment by bradhawkins85** [comment]
Hi,
I know this is an old issue but i found the above solution "I missed the instruction to download and install https://github.com/mjg59/python-broadlink" did not work for me on my Raspberry Pi, despite the package being installed I still got the same error.

If found the following resolved the issue:
pip uninstall broadlink
pip install broadlink

Hope this helps someone else in the future.

Brad
