### ISSUE TITLE
AC control

### ISSUE THREAD

**Issue by adrianmihalko** [davorf/BlackBeanControl#22]
This is not an issue, but rather than a feature request: is there any way to send complex commands like  controlling an AC? In default Broadlink app it is possible.

1, fan speed (low, med, high)
2, mode (heating, cooling, drying, etc)
3, temperature
4, on/off

...as one command. 

All suggestions are welcomed.

**Comment by davorf** [comment]
Hello!

Firstly, sorry for the late response. You could make a .bat or .vbs file and send separate commands consecutively (if you're using it on Windows), or use some other scripting/batch if you're using Linux. 

Best regards,
Davor
