### ISSUE TITLE
Multiple commands

### ISSUE THREAD

**Issue by yavinmaster** [davorf/BlackBeanControl#25]
How do you send multiple commands in sequence without making multiple calls of the software?

Thanks.

**Comment by davorf** [comment]
Hello!

You can't do it by using script only. You could either make a batch file with multiple calls, or, if you are using it in OpenHAB, you can do that using rules.

Best regards,
Davor

**Comment by yavinmaster** [comment]
OK thanks for the quick reply.  I'm currently doing it with OpenHAB but the ESP8266 version I previously used allowed multiple signals to be sent in one call, which reduced the delays and network traffic.

**Comment by davorf** [comment]
Hello!

I'm not sure what you're controlling with it, but, in my case (controlling Samsung TV and LG Air Condition) sending commands in a quick succession didn't work. I've had to add pauses between commands to make it work, because TV would not recognize them all. 

Best regards,
Davor
