### ISSUE TITLE
Any way to forward the received IR commands?

### ISSUE THREAD

**Issue by eaglerbits** [davorf/BlackBeanControl#29]
First, thanks for this great job!

Now, my question:
I’m using Broadlink to send IR commands from my Openhab and works great!
Best would be if we can forward the Received IR commands from Broadlink to Openhab.
That option would be amazing to open a new way to interact with home doing thinks like turning lights with unused remote tv buttons (just a small sample).
Thanks

**Comment by davorf** [comment]
Hello!

I'm not sure this could be done. The only way to receive IR command is to put RM in a learning mode. And the only way to do it (as far as I know) is to send a command over a network. So, you would need some device on the network (OpenHAB UI for example) to put it in learning mode before pressing button on the remote, so the whole forwarding thing doesn't make sense - if you are going to use OpenHAB UI to put it in learning mode, you could also turn lights ON/OFF with OpenHAB UI directly. 

Best regards,
Davor
