### ISSUE TITLE
sample data?

### ISSUE THREAD

**Issue by remb0** [davorf/BlackBeanControl#3]
can you give a little description how the dummy and other data must look like?

**Comment by davorf** [comment]
Hello! 

This is how the BlackBeanControl.ini file should look like:

```
[General]
IPAddress: 192.168.0.100
Port: 80

[Commands]
VolumeUp: 5aa5aa555aa5aa55000000000000000000000000000000000000000000000000d5f4000037276a000480cf1ee40d43b40100000074c6000054d411c45ce1b0c972dd0116fea3bcda6885ba57b5128cb5b87b946529c240b59b8bed235aef386f074cec4331af96da9650c2378197ef947dda6361c843d7fa30fca49fa58192dc08e7d0d9b59c9a7d
```

Remember that you have to change an IP address to the real IP of your RM3 Mini. The VolumeUp UDP payload is just your sample from the OpenHAB forum, and it definitely looks alright to me. As far as I know, every payload should begin with this 5aa5 part. Regarding a dummy command, it's no longer needed, and does not exists in the new version. When you want to add a new command, just name it without blanks (for example ChannelUp), followed by column, and then insert the payload of that command. You should be able to have as much commands as you need, as long as you are following this convention. 

Best regards,
Davor
