### ISSUE TITLE
Auth failure with 2nd RM3 Mini

### ISSUE THREAD

**Issue by mcgheffe** [davorf/BlackBeanControl#44]
I have BlackBeanControl working for a few weeks now on an RM3 mini (device I purchased over a year ago).  Today I attempted to add a second RM3 mini in another room (Just purchased this one from Amazon, more than a year newer than the other).  I added a new device section to the .ini file but I cannot get past an auth failure with the new RM3.  Nothing I've tried works and I'm stuck.  Am I missing something?  Is it possible that the authentication key has changed in the firmware?

```
Traceback (most recent call last):
  File "./BlackBeanControl.py", line 168, in <module>
    RM3Device.auth()
  File "/usr/local/lib/python2.7/dist-packages/broadlink-0.14.1-py2.7.egg/broadlink/__init__.py", line 271, in auth
    check_error(response[0x22:0x24])
  File "/usr/local/lib/python2.7/dist-packages/broadlink-0.14.1-py2.7.egg/broadlink/exceptions.py", line 97, in check_error
    raise exception(error_code)
broadlink.exceptions.AuthenticationError: Authentication failed
```

The working device has firmware version "v57", but the failing device has firmware version "v44057".

Thanks!

**Comment by johnhughbowen** [comment]
You right, Broardlink changed their authentication so they can charge 2,000 to integrate to their API which works on ios or Android only. There seems no way around this, which seems a little silly as they are destroying probably their biggest market.
You can still but the old ones, but you will need to hunt around and ask the right questions.
There is no way to flash the firmware to go back to a previous version.
You will find lots of comments about this on the Web, but it's not true there is international Versions and Chinese versions of the software.
I have had long conversations with Broardlink about this but with no successful outcome.

**Comment by johnhughbowen** [comment]
If your intrested you can find their API here https://docs.ibroadlink.com/public/configuration-sdk+ctc/sdk-integrations_-_configuration/
It works with both the cloud and local control, although that's not obvious from the documentation.

**Comment by mcgheffe** [comment]
Thanks for the info.  This is frustrating and unfortunate that they've broken a very handy use case for this device.

**Comment by flagg19** [comment]
Hi, I have a RM3 Mini with the latest firmware and I solved this auth problem by disabling the lock on the official broadlink app:
This screenshot is in italian but it should be easy to see where to find the option:

![image](https://user-images.githubusercontent.com/1681032/95018103-c282a880-065d-11eb-8fcd-c0e807e25cd9.png)

**Comment by mcgheffe** [comment]
That's a good tip. Thanks!  That does get past the auth error but unfortunately now I'm left with the "storage full" error. Hopefully a fix for that will be found soon.

**Comment by johnhughbowen** [comment]
> Hi, I have a RM3 Mini with the latest firmware and I solved this auth problem by disabling the lock on the official broadlink app:
> This screenshot is in italian but it should be easy to see where to find the option:

Quick One, Where is this screen?

**Comment by mcgheffe** [comment]
View the IR Blaster device in the app, then click the dots in the upper-right corner (that's where it is in my Android).

**Comment by johnhughbowen** [comment]
Ahh, Not there on the iPhone (On mine at least)
Will try to get hold of Android and try.
![device info 2](https://user-images.githubusercontent.com/71754244/95105969-cb43af00-072f-11eb-83c3-5b325a8dbe25.png)
![Device Info](https://user-images.githubusercontent.com/71754244/95105970-cbdc4580-072f-11eb-8866-5338afe158bb.png)

**Comment by flagg19** [comment]
> That's a good tip. Thanks! That does get past the auth error but unfortunately now I'm left with the "storage full" error. Hopefully a fix for that will be found soon.

Yea I got that too, and I'm sorry I have no direct solution for that. While I was investigating the issue I ended up on [the page](https://github.com/mjg59/python-broadlink/issues/404) of the repo that provides the library used by this repo and found that using it directly it works.

I think this commit contains what fixed the storage problem for the broadlink_cli script on the other repo: https://github.com/mjg59/python-broadlink/pull/369/commits/9cda686d24a7968450051f36f8519891f044441a maybe the same approach could be used here.

**Comment by flagg19** [comment]
> Ahh, Not there on the iPhone (On mine at least)
> Will try to get hold of Android and try.

I stumbled upon that option by chance, there's no mention of it anywhere on the internet so it's probably something new that maybe hasn't arrived on iOS yet
