### ISSUE TITLE
control multiple Mini?

### ISSUE THREAD

**Issue by farhanito** [davorf/BlackBeanControl#5]
hi,

what's the easiest method to control more than one Minis?

thanks

**Comment by davorf** [comment]
Hello!

I'm not sure what do you mean? Do you want to send the same command to more than one RM 3 at a time, or you just want to be able to send commands with a same script to specific RM 3. If the latter is the case, then you can specify IP Address, Port and MAC Address of the RM 3 you want to use as parameter, when calling BlackBeanControl.py.

Best regards,
Davor

**Comment by farhanito** [comment]
Yes, i mean, is it possible to define multiple devices in the .ini file? 

For example :

```
[RM3-A]
IP =
PORT =
MAC =
Timeout =

[RM3-B]
IP =
PORT =
MAC =
Timeout =
```

and then call 
`BlackBeanControl.py [command] [RM3-A]`

Something like that. 

Thanks

**Comment by davorf** [comment]
Hello!

At the moment, it's not possible to define multiple RM 3 device parameters in BlackBeanControl.ini, but you can accomplish the same thing by using IP Address, Port and MAC Address parameters when calling the script. That way, command line parameters will override BlackBeanControl.ini settings. The only disadvantage of this approach is a longer command line call. But it should work just the same.

Best regards,
Davor

**Comment by farhanito** [comment]
I see, 

thanks

**Comment by davorf** [comment]
Hello @farhanito 

I've pushed changes made to BlackBeanControl.py to the github. Now you can have additional sections in BlackBeanControl.ini, and use it with -d (--device) parameter. Section names must not contain spaces, and additional section must have all the options General section has (IPAddress, Port, MACAddress and Timeout). I've added -t (--timeout) parameter too (custom Timeout parameter). There is also a validation, so you can't use -d (--device) parameter in conjunction with other parameters (-i, -p, -m, -t), and you can't use other parameters selectively (you either use all of them, or none - again, for -i, -p, -m and -t). If you have any problems or question, feel free to write about it here. I would appreciate a feedback, after you test a new version of the script.

Best regards,
Davor

**Comment by farhanito** [comment]
Hi, thanks for the new script. 

Just tested it, and got this error :

osmc@osmc:~/BlackBeanControl$ python BlackBeanControl.py -c LedOn
Traceback (most recent call last):
  File "BlackBeanControl.py", line 172, in <module>
    RM3Device.enter_learning()
AttributeError: device instance has no attribute 'enter_learning'
osmc@osmc:~/BlackBeanControl$

What could possibly be the issue?

**Comment by davorf** [comment]
Hello!

I've just tried all the possible combinations (learning without parameters, with a device parameter, with a separate parameters, and executing command without parameters, with a device parameter and with a separate parameters) and it all works as it was working before. Have you changed anything else, besides a new version of the script? Have you checked BlackBeanControl.ini for errors? 

Best regards,
Davor

**Comment by luiscampiz** [comment]
Hello @davorf 
Thanks for this script.
I have the same problem as @farhanito:
mbp-de-luis:BlackBeanControl-master luiscampiz$ python BlackBeanControl.py -c TV_ON
Traceback (most recent call last):
  File "BlackBeanControl.py", line 172, in <module>
    RM3Device.enter_learning()
AttributeError: device instance has no attribute 'enter_learning'

Any idea?

**Comment by luiscampiz** [comment]
Hello @davorf @farhanito 
The problem was some changes in python-broadlink master branch.
It is working now whit a little change in BlackBeanControl.py. Line 152.
`RM3Device = broadlink.rm((RealIPAddress, RealPort), RealMACAddress)`
I don't know the implications of that change, but is working for me.

**Comment by farhanito** [comment]
Can confirm. 
Thanks @luiscampiz

**Comment by davorf** [comment]
Hello!

@luiscampiz thank you for investigating an issue more thorough. I haven't updated broadlink packaged - that's why it worked for me. I'm going to update it tonight, apply your change and test it. If everything works as it should, I will push changes to the repository. Thank you for your help.

Best regards,
Davor

**Comment by davorf** [comment]
Hello!

I've applied, tested and pushed changes @luiscampiz  mentioned. Now the script is working with a latest Broadlink Python package. I'm closing this issue, so, if you find any other problem, feel free to open a new one. 

Best regards,
Davor
