### ISSUE TITLE
Alexa control

### ISSUE THREAD

**Issue by geoffacielo** [davorf/BlackBeanControl#6]
Alexa applet to control tv

**Comment by davorf** [comment]
Hello!

I'm not sure I understand what you mean with this? Are you asking for some Alexa specific add-on, or are you trying to use this script with Alexa? I don't have Alexa, so, I'm not familiar with it. 

Best regards,
Davor

**Comment by davorf** [comment]
Hello! 

Since there is no new information regarding this issue, I will close it. If you have any new or additional information, feel free to open a new issue.

Best regards,
Davor
