### ISSUE TITLE
Not entering learning mode...

### ISSUE THREAD

**Issue by ChopOMatic** [davorf/BlackBeanControl#8]
When running the script, I always get this error:

`-bash: BlackBeanControl.ini: command not found`

There is no indication that the RM3Mini ever enters learning mode, however, and there is never any change made to the .ini file.

What am I missing?

Thx!

**Comment by davorf** [comment]
Hello!

Sorry for the late reply. It could be a problem with the broadlink-python package version. I haven't tried a latest version, but I've seen a lot of changes lately. I will try using BlackBeanControl with a latest version of the broadlink-python package and see if I can reproduce an error. 

Best regards,
Davor

**Comment by ChopOMatic** [comment]
Thx, Davor. Got it working. Sorry I didn't update the issue! It was just a
path problem with my setup. Big thx for coding this!




Jerry Hatchett, CCE, EnCE

Certified Computer Examiner
EnCase Certified Examiner
Licensed Private Investigator (Texas PSB License #A18333)

Omni:  713-364-2467



DISCLAIMER:  Anything I say, particularly with regard to technology, should
be interpreted generally, not specifically. The online world is a wonderful
thing, but rarely is it practical to cover every imaginable scenario in a
written, fast-paced forum. There are often exceptions, so keep that in mind.

**Comment by davorf** [comment]
Hello!

No problem, I'm glad you made it work. 

Best regards,
Davor

**Comment by Korax76** [comment]
Hello,
I seem to have the same problem using Rasbian Strech.
The setup worked fine with Jessie, but latest Strech build, it is impossible to enter Learning mode: command not found. 
I have tried to set `chmod 777` on all related py files but no difference in behaviour. The LED will not turn on. Correct IP/ MAC, etc. Have anybody else seen this problem lately and is there any debug switch to turn on?

Thanks for a great code, excellent plugin when using Domoticz!
Rpi2B,
Rasbian Strech, Version 9.
