### ISSUE TITLE
Cannot send a pre-learned command on one device to another device

### ISSUE THREAD

**Issue by walkention** [davorf/BlackBeanControl#9]
It seems as though if I have learned a command on one device it can't be sent to another device. It doesn't put the other device in learning mode and no error is thrown.

If I use the [python-broadlink](https://github.com/mjg59/python-broadlink) package directly I can learn a command on one and send it to both devices.

Here's the sample code I'm using to learn a command using python-broadlink:
```
#!/usr/bin/python

import broadlink
import time

print "discover"
devices = broadlink.discover(timeout=5)
device = devices[1]
device.auth()
print "enter_learning"
device.enter_learning()
print "sleep"
time.sleep(5)
print "check data"
ir_packet = device.check_data()
print str(ir_packet).encode('hex')
```

I'm taking the output from a learned command and putting it into this script to send it to both devices:

```
#!/usr/bin/python

import broadlink
import time

hex_ir_packet = "260070004f13141327141314141328131314141328131314131414131500035f4e14141328121513131428131314131427141413131414131400035e4f14141328131413141328131413141327141413141315121500035f4e141413271315131413281314131413271414131314141314000d050000000000000000"
ir_packet = hex_ir_packet.decode('hex')

print "discover"
devices = broadlink.discover(timeout=5)
device = devices[0]
device.auth()
print "Send command to device 1"
device.send_data(ir_packet)
print "wait"
time.sleep(2)
device = devices[1]
device.auth()
print "Send command to device 2"
device.send_data(ir_packet)
```

It looks as though in your package the learned command has four bytes of zero padding added, is decrypted using the device auth key, and then stored in the BlackBeanControl.ini file. Perhaps the decrypting the packet with the device key makes it unable to be re-encrypted with a different device key. 

This functionality may be by design to prevent a command learned on once device to be sent to another, but it might be nice to broadcast the same command to a different device/room by learning it once on another device.

I forked this packaged and was going to try and rewrite the code for learning and sending commands.  I would try to write the commands as encoded hex and make a way to migrate codes from the old to the new format so they don't have to be re-learned again.

Let me know what you think.

Thanks for building this package! It's working great with my Alexa integration code that I am planning on releasing here soon! :-)

**Comment by davorf** [comment]
Hello!

Since I own only one RM3 Mini, I wasn't able to test it properly. Regardless, I don't think encryption has anything to do with it, since the encryption Key and IV are hard-coded inside broadlink-python package. They are the same for every device. I'll take a look at this, probably tonight, and report back my findings.

Best regards,
Davor

**Comment by walkention** [comment]
I had thought that too until I started poking around in the python-broadlink code. In that code it looks like there is an initial key used for auth and then that key is reset from the payload data returned in auth() [here](https://github.com/mjg59/python-broadlink/blob/master/broadlink/__init__.py#L185). That data then overwrites the self.key on [line 190](https://github.com/mjg59/python-broadlink/blob/master/broadlink/__init__.py#L190). If each device returns a device specific key after auth() that would impact using the saved data on another device from the BlackBeanControl.ini.

In [this issue](https://github.com/mjg59/python-broadlink/issues/10#issuecomment-266241723) it is discussed how the data returned seems to be the raw IR data with some header info attached. It might be helpful to have the raw IR data stored in the BlackBeanControl.ini so folks could pull shared codes online without having to learn them, assuming the header info can be figured out.

I [re-wrote how codes were stored](https://github.com/davorf/BlackBeanControl/compare/master...walkention:master) in your script to save the IR data in raw form and created a re-key utility to convert commands to raw storage. It works with my two RM3's pretty well. Let me know if you want me to issue a pull request for this update.

Thanks!

**Comment by davorf** [comment]
Hello! 

You can issue a pull request. I'll just review your naming and README.md (for consistency) and remove any commented parts of the code. Thank you for the contribution. 

Best regards,
Davor

**Comment by davorf** [comment]
Hello!

Thank you for your contribution once again. I'll review and accept your pull request as soon as I can - probably tonight, or tomorrow.

Best regards,
Davor

**Comment by walkention** [comment]
Davor,

No rush. Thanks for reviewing it and giving your feedback! If you want to make any changes or additions or want to discuss anything just let me know.

Thanks!
Aydaen

**Comment by davorf** [comment]
Hello!

I'm not sure if I merged this correctly (haven't used git as source control before, especially merging pull requests part), but I think it should work. I've made another pull request by mistake, so, I would really appreciate if you could check if the code works as it should. 

Best regards,
Davor

**Comment by walkention** [comment]
Hey!

I just pulled down the latest code in your master branch and everything works that was in the pull request! I think it's set! Thanks for processing that pull request and all the work you did on this project!

Aydaen
